
<form action="zomato.php" method="GET">
  Search By Location <input type="text" name="zomquery">
  <input type="submit" name="zomsubmit" value="Search">
</form>


<?php
if (isset($_GET['zomsubmit'])) {
  $zomquery = $_GET['zomquery'];
  # Continue running code
}
else {
  //echo "Search key not found";
  exit();
}
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://developers.zomato.com/api/v2.1/searchQuery?q=".$zomquery."&start=0&count=10");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
$headers = array(
  "Accept: application/json",
  "User-Key: bbfd0476d9565ed6a2faaf257978bb6a"
  );
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

$zomdata = json_decode($result);
print_r($zomdata);
for($i=0;$i<10;$i++){
$zomrestaurants[$i] = $zomdata[$i]->restaurants;
//echo "<pre>"; print_r($zomrestaurants); echo "</pre>";
    if (count($zomrestaurants) == 0) {
      echo "<b>No results found for your search query</b>"; 
      exit();
    }
}
for($i=0;$i<10;$i++){
 echo "Found: ".$zomdata[$i]->results_found." results<br/>";
 echo "Result shown: ".$zomdata[$i]->results_start." to ".$zomdata[$i]->results_shown."<br/><br/>";
}
foreach ($zomrestaurants as $restaurant) {
  echo "<h3>".@$restaurant->restaurant->name."</h3>";
    
  
  echo "Restaurant ID: ".@$restaurant->restaurant->id."<br/>";
  echo "User rating: ".@$restaurant->restaurant->user_rating->rating_text."( ".@$restaurant->restaurant->user_rating->aggregate_rating."/5 ) Depending upon ".@$restaurant->restaurant->user_rating->votes." votes<br/>";
  echo @$restaurant->restaurant->location->address.", ".@$restaurant->restaurant->location->city." <a href='".@$restaurant->restaurant->url."'>Visit restaurant page</a><br/>";
  echo "<br/><hr>";
  //echo "<pre>"; print_r($restaurant->restaurant); echo "</pre>";

}
?>